name: Send trigger for updating robottelo image on quay.
on:
  push:

jobs:
  trigger-robottelo-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in robottelo repo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CHERRYPICK_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/jameerpathan111/testing_repo1/actions/workflows/workflow1.yml/dispatches \
            -d '{"ref":"'"${GITHUB_REF##*/}"'"}'          
